apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec: # configuration of the deployment
  replicas: 1
  selector: # selects the pods it should control
    # matchLabels: 
    #   app: second-app
    #   tier: backend
    matchExpressions:
      - {key: app, operator: In, values: [second-app, first-app]}
  template: # pod template, don't have to add kind: pod
    metadata:
      labels:
        app: second-app
        tier: backend
    spec: # configuration of the individual pod
      containers:
        - name: second-node
          image: <dockerhubname>/kub-first-app:2
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 3
            initialDelaySeconds: 5
