# Service
apiVersion: v1
kind: Service # service object exposes paths to the cluster or to the outside world
metadata:
  name: backend
spec:
  selector:
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec: # configuration of the deployment
  replicas: 1
  selector: # selects the pods it should control
    # matchLabels: 
    #   app: second-app
    #   tier: backend
    matchExpressions:
      - {key: app, operator: In, values: [second-app, first-app]}
  template: # pod template, don't have to add kind: pod
    metadata:
      labels:
        app: second-app
        tier: backend
    spec: # configuration of the individual pod
      containers:
        - name: second-node
          image: <dockerhubname>/kub-first-app:2
        # - name: ...
        #   image: ...
