apiVersion: v1
kind: Service # service object exposes paths to the cluster or to the outside world
metadata:
  name: backend
spec:
  selector:
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer
